# Setup
lang: ja
title: つかさの哲学原理
description: 泣かず、笑わず、ただ理解せよ
avatar: /avatar.jpeg
cover_image: /bg.jpeg
timezone: Asia/Tokyo

# kramdown
kramdown:
  hard_wrap: true

# plugin
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
# Optimize Jekyl SEO Tag
twitter:
  username: tukasa1900
logo: logo.png
social:
  name: tukasa
  links:
    - https://twitter.com/tukasa1900
    - https://github.com/tukasa

# use sass
sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: tukasa
  url: https://github.com/tukasa/
  email: alpha01tks@gmail.com

# Build settings
collections_dir: my_collections
collections:
  ethica:
    output: true
    permalink: /thesis/ethica/:name
  ethica2:
    output: true
    permalink: /thesis/ethica2/:name
  historyofphilosophy:
    output: true
    permalink: /thesis/historyofphilosophy/:name
  ducontratsocial:
    output: true
    permalink: /thesis/ducontratsocial/:name
  authors:
    output: true
  basic:
    output: true
  thesis:
    output: true
defaults:
  - scope:
      path: ""
      type: "ethica"
    values:
      layout: "chapter"
      parenttitle: "スピノザ『エチカ』の考察"
      parenturl: "/thesis/ethica/"
  - scope:
      path: ""
      type: "ethica2"
    values:
      layout: "chapter"
      parenttitle: "スピノザ『エチカ』の考察"
      parenturl: "/thesis/ethica2/"
  - scope:
      path: ""
      type: "historyofphilosophy"
    values:
      layout: "chapter"
      parenttitle: "一時間でわかる近世哲学史"
      parenturl: "/thesis/historyofphilosophy/"
  - scope:
      path: ""
      type: "ducontratsocial"
    values:
      layout: "chapter"
      parenttitle: "ルソー『社会契約論』の考察"
      parenturl: "/thesis/ducontratsocial/"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "thesis"
    values:
      layout: "thesis"
